-- Seed for sla_license_codes, from the LEAP decoder
-- (leap-license-type-and-class-definitions.xlsx). Run once after schema.sql.
-- Field is intentionally backwards: it's easier to prove what is NOT a bodega.
-- `not_bodega = true`  => obviously not a bodega (liquor/wine stores, wholesalers,
--                         manufacturers, restaurants, hotels, clubs, venues, B&Bs...).
-- `not_bodega = false` => a bodega candidate (Grocery Store) or a vague label.
-- Idempotent: re-running reconciles description/product/not_bodega, no duplicates.

INSERT INTO sla_license_codes (type_code, class_code, class_description, product, not_bodega) VALUES
  (1, 1,   'Wholesale Beer (Retail)',                  'Beer',                true),
  (1, 2,   'Wholesale Beer',                           'Beer',                true),
  (1, 5,   'Cider Producer',                           'Cider',               true),
  (1, 7,   'Wholesale Wine',                           'Wine',                true),
  (1, 9,   'Wholesale Liquor',                         'Liquor',              true),
  (1, 11,  'Importer',                                 NULL,                  true),
  (1, 13,  'Brewer',                                   'Beer',                true),
  (1, 14,  'Micro-Brewer',                             'Beer',                true),
  (1, 15,  'Farm Brewer',                              'Beer',                true),
  (1, 16,  'Custom Beermaker''s Center',               'Beer',                true),
  (1, 20,  'Mead Producer',                            'Mead',                true),
  (1, 21,  'Farm Meadery',                             'Mead',                true),
  (1, 24,  'Cider Producer (Manufacturer)',            'Cider',               true),
  (1, 25,  'Farm Cidery',                              'Cider',               true),
  (1, 26,  'Custom Cidermaker''s Center',              'Cider',               true),
  (1, 31,  'Winery',                                   'Wine',                true),
  (1, 32,  'Farm winery',                              'Wine',                true),
  (1, 33,  'Special Winery',                           'Wine',                true),
  (1, 34,  'Special Farm Winery',                      'Wine',                true),
  (1, 35,  'Custom Winemaker''s Center',               'Wine',                true),
  (1, 36,  'Direct Shipper',                           'Wine',                true),
  (1, 37,  'MicroFarm Winery',                         'Wine',                true),
  (1, 38,  'Satellite Wine Store',                     'Wine',                true),
  (1, 51,  'Distiller Class A',                        'Liquor',              true),
  (1, 52,  'Distiller Class A-1 (Micro-distiller)',    'Liquor',              true),
  (1, 53,  'Distiller Class B',                        'Liquor',              true),
  (1, 54,  'Distiller Class B-1 (Micro-rectifier)',    'Liquor',              true),
  (1, 55,  'Distiller Class C (Fruit Brandy Producer)','Liquor',              true),
  (1, 56,  'Distiller Class D (Farm Distiller)',       'Liquor',              true),
  (1, 71,  'Grocery Store',                            'Beer',                false),
  (1, 72,  'Drug Store',                               'Beer',                true),
  (1, 73,  'Supply Ship',                              'Beer',                true),
  (1, 74,  'Vendor',                                   'Beer',                false),
  (1, 81,  'Grocery Store',                            'Beer & Wine Products',false),
  (1, 82,  'Drug Store',                               'Beer & Wine Products',true),
  (1, 83,  'Supply Ship',                              'Beer & Wine Products',true),
  (1, 91,  'Wine Store',                               'Wine',                true),
  (1, 92,  'Roadside Farm Market',                     'Wine',                true),
  (1, 100, 'Liquor Store',                             'Liquor',              true),
  (1, 101, 'Off Premises Caterer',                     'Liquor',              true),
  (1, 111, 'Restaurant',                               'Beer',                true),
  (1, 112, 'Summer Restaurant',                        'Beer',                true),
  (1, 113, 'Winter Restaurant',                        'Beer',                true),
  (1, 114, 'Hotel',                                    'Beer',                true),
  (1, 115, 'Summer Hotel',                             'Beer',                true),
  (1, 116, 'Winter Hotel',                             'Beer',                true),
  (1, 117, 'Catering Establishment',                   'Beer',                true),
  (1, 118, 'Summer Catering Establishment',            'Beer',                true),
  (1, 119, 'Winter Catering Establishment',            'Beer',                true),
  (1, 120, 'Club',                                     'Beer',                true),
  (1, 121, 'Summer Club',                              'Beer',                true),
  (1, 122, 'Winter Club',                              'Beer',                true),
  (1, 123, 'Railroad car',                             'Beer',                true),
  (1, 124, 'Summer Railroad Car',                      'Beer',                true),
  (1, 125, 'Winter Railroad Car',                      'Beer',                true),
  (1, 126, 'Vessel',                                   'Beer',                true),
  (1, 127, 'Summer Vessel',                            'Beer',                true),
  (1, 128, 'Winter Vessel',                            'Beer',                true),
  (1, 129, 'Aircraft',                                 'Beer',                true),
  (1, 130, 'Summer Aircraft',                          'Beer',                true),
  (1, 131, 'Winter Aircraft',                          'Beer',                true),
  (1, 132, 'Bed & Breakfast',                          'Beer',                true),
  (1, 133, 'Summer Bed & Breakfast',                   'Beer',                true),
  (1, 134, 'Winter Bed & Breakfast',                   'Beer',                true),
  (1, 135, 'Misc- Not Primary Source of Revenue',      'Beer',                true),
  (1, 136, 'Summer Misc- Not primary Source of Revenue','Beer',               true),
  (1, 137, 'Winter Misc- Not Primary Source of Revenue','Beer',               true),
  (1, 138, 'Food & Beverage Business',                 'Beer',                true),
  (1, 139, 'Summer Food & Beverage Business',          'Beer',                true),
  (1, 140, 'Winter Food & Beverage Business',          'Beer',                true),
  (1, 141, 'Legitimate Theatre',                       'Beer',                true),
  (1, 142, 'Summer Legitimate Theatre',                'Beer',                true),
  (1, 143, 'Winter Legitimate Theatre',                'Beer',                true),
  (1, 144, 'Concert Hall',                             'Beer',                true),
  (1, 145, 'Summer Concert Hall',                      'Beer',                true),
  (1, 146, 'Winter Concert Hall',                      'Beer',                true),
  (1, 147, 'Opera House',                              'Beer',                true),
  (1, 148, 'Summer Opera House',                       'Beer',                true),
  (1, 149, 'Winter Opera House',                       'Beer',                true),
  (1, 150, 'Bowling Establishment',                    'Beer',                true),
  (1, 151, 'Summer Bowling Establishment',             'Beer',                true),
  (1, 152, 'Winter Bowling Establishment',             'Beer',                true),
  (1, 153, 'Public Dance Hall',                        'Beer',                true),
  (1, 154, 'Summer Public Dance Hall',                 'Beer',                true),
  (1, 155, 'Winter Public Dance Hall',                 'Beer',                true),
  (1, 156, 'Night Club',                               'Beer',                true),
  (1, 157, 'Summer Night Club',                        'Beer',                true),
  (1, 158, 'Winter Night Club',                        'Beer',                true),
  (1, 159, 'Golf Venue',                               'Beer',                true),
  (1, 160, 'Summer Golf Venue',                        'Beer',                true),
  (1, 161, 'Winter Golf Venue',                        'Beer',                true),
  (1, 162, 'Tennis Venue',                             'Beer',                true),
  (1, 163, 'Summer Tennis Venue',                      'Beer',                true),
  (1, 164, 'Winter Tennis Venue',                      'Beer',                true),
  (1, 165, 'Swimming Venue',                           'Beer',                true),
  (1, 166, 'Summer Swimming Venue',                    'Beer',                true),
  (1, 167, 'Winter Swimming Venue',                    'Beer',                true),
  (1, 168, 'Skiing Venue',                             'Beer',                true),
  (1, 169, 'Summer Skiing Venue',                      'Beer',                true),
  (1, 170, 'Winter Skiing Venue',                      'Beer',                true),
  (1, 171, 'Ice Skating Venue',                        'Beer',                true),
  (1, 172, 'Summer Ice Skating Venue',                 'Beer',                true),
  (1, 173, 'Winter Ice Skating Venue',                 'Beer',                true),
  (1, 174, 'Boating Venue',                            'Beer',                true),
  (1, 175, 'Summer Boating Venue',                     'Beer',                true),
  (1, 176, 'Winter Boating Venue',                     'Beer',                true),
  (1, 177, 'Athletic/Sporting Event/Expositions/Large Gathering Venue',       'Beer', true),
  (1, 178, 'Summer Athletic/Sporting Event/Expositions/Large Gathering Venue','Beer', true),
  (1, 179, 'Winter Athletic/Sporting Event/Expositions/Large Gathering Venue','Beer', true),
  (1, 180, 'Excursion & Sight Seeing Vessels',         'Beer',                true),
  (1, 181, 'Summer Excursion & Sight Seeing Vessel',   'Beer',                true),
  (1, 182, 'Winter Excursion & Sight Seeing Vessels',  'Beer',                true),
  (1, 183, 'Race Tracks',                              'Beer',                true),
  (1, 184, 'Summer Race Tracks',                       'Beer',                true),
  (1, 185, 'Winter Race Tracks',                       'Beer',                true),
  (1, 186, 'Outdoor Athletic Fields and Stadiums',     'Beer',                true),
  (1, 187, 'Summer Outdoor Athletic Fields and Stadiums','Beer',              true),
  (1, 188, 'Winter Outdoor Athletic Fields and Stadiums','Beer',              true),
  (1, 189, 'Additional bar- ball park, race track, etc','Beer',              true),
  (1, 240, 'Restaurant',                               'Wine',                true),
  (1, 241, 'Summer Restaurant',                        'Wine',                true),
  (1, 242, 'Winter Restaurant',                        'Wine',                true),
  (1, 243, 'Hotel',                                    'Wine',                true),
  (1, 244, 'Summer Hotel',                             'Wine',                true),
  (1, 245, 'Winter Hotel',                             'Wine',                true),
  (1, 246, 'Catering Establishment',                   'Wine',                true),
  (1, 247, 'Summer Catering Establishment',            'Wine',                true),
  (1, 248, 'Winter Catering Establishment',            'Wine',                true),
  (1, 249, 'Club',                                     'Wine',                true),
  (1, 250, 'Summer Club',                              'Wine',                true),
  (1, 251, 'Winter Club',                              'Wine',                true),
  (1, 252, 'Railroad Car',                             'Wine',                true),
  (1, 253, 'Summer Railroad Car',                      'Wine',                true),
  (1, 254, 'Winter Railroad Car',                      'Wine',                true),
  (1, 255, 'Vessel',                                   'Wine',                true),
  (1, 256, 'Summer Vessel',                            'Wine',                true),
  (1, 257, 'Winter Vessel',                            'Wine',                true),
  (1, 258, 'Aircraft',                                 'Wine',                true),
  (1, 259, 'Summer Aircraft',                          'Wine',                true),
  (1, 260, 'Winter Aircraft',                          'Wine',                true),
  (1, 261, 'Bed & Breakfast',                          'Wine',                true),
  (1, 262, 'Summer Bed & Breakfast',                   'Wine',                true),
  (1, 263, 'Winter Bed & Breakfast',                   'Wine',                true),
  (1, 264, 'Misc- Not Primary Source of Revenue',      'Wine',                true),
  (1, 265, 'Summer Misc- Not Primary Source of Revenue','Wine',               true),
  (1, 266, 'Winter Misc- Not Primary Source of Revenue','Wine',               true),
  (1, 267, 'Food & Beverage Business',                 'Wine',                true),
  (1, 268, 'Summer Food & Beverage Business',          'Wine',                true),
  (1, 269, 'Winter Food & Beverage Business',          'Wine',                true),
  (1, 270, 'Legitimate Theatre',                       'Wine',                true),
  (1, 271, 'Summer Legitimate Theatre',                'Wine',                true),
  (1, 272, 'Winter Legitimate Theatre',                'Wine',                true),
  (1, 273, 'Concert Hall',                             'Wine',                true),
  (1, 274, 'Summer Concert Hall',                      'Wine',                true),
  (1, 275, 'Winter Concert Hall',                      'Wine',                true),
  (1, 276, 'Opera House',                              'Wine',                true),
  (1, 277, 'Summer Opera House',                       'Wine',                true),
  (1, 278, 'Winter Opera House',                       'Wine',                true),
  (1, 279, 'Bowling Establishment',                    'Wine',                true),
  (1, 280, 'Summer Bowling Establishment',             'Wine',                true),
  (1, 281, 'Winter Bowling Establishment',             'Wine',                true),
  (1, 282, 'Public Dance Hall',                        'Wine',                true),
  (1, 283, 'Summer Public Dance Hall',                 'Wine',                true),
  (1, 284, 'Winter Public Dance Hall',                 'Wine',                true),
  (1, 285, 'Night Club',                               'Wine',                true),
  (1, 286, 'Summer Night Club',                        'Wine',                true),
  (1, 287, 'Winter Night Club',                        'Wine',                true),
  (1, 288, 'Golf Venue',                               'Wine',                true),
  (1, 289, 'Summer Golf Venue',                        'Wine',                true),
  (1, 290, 'Winter Golf Venue',                        'Wine',                true),
  (1, 291, 'Tennis Venue',                             'Wine',                true),
  (1, 292, 'Summer Tennis Venue',                      'Wine',                true),
  (1, 293, 'Winter Tennis Venue',                      'Wine',                true),
  (1, 294, 'Swimming Venue',                           'Wine',                true),
  (1, 295, 'Summer Swimming Venue',                    'Wine',                true),
  (1, 296, 'Winter Swimming Venue',                    'Wine',                true),
  (1, 297, 'Skiing Venue',                             'Wine',                true),
  (1, 298, 'Summer Skiing Venue',                      'Wine',                true),
  (1, 299, 'Winter Skiing Venue',                      'Wine',                true),
  (1, 300, 'Ice Skating Venue',                        'Wine',                true),
  (1, 301, 'Summer Ice Skating Venue',                 'Wine',                true),
  (1, 302, 'Winter Ice Skating Venue',                 'Wine',                true),
  (1, 303, 'Boating Venue',                            'Wine',                true),
  (1, 304, 'Summer Boating Venue',                     'Wine',                true),
  (1, 305, 'Winter Boating Venue',                     'Wine',                true),
  (1, 306, 'Race Tracks',                              'Wine',                true),
  (1, 307, 'Summer Race Tracks',                       'Wine',                true),
  (1, 308, 'Winter Race Tracks',                       'Wine',                true),
  (1, 309, 'Athletic/Sporting Event/Expositions/Large Gathering Venue',       'Wine', true),
  (1, 310, 'Summer Athletic/Sporting Event/Expositions/Large Gathering Venue','Wine', true),
  (1, 311, 'Winter Athletic/Sporting Event/Expositions/Large Gathering Venue','Wine', true),
  (1, 312, 'Excursion & Sight Seeing Vessels',         'Wine',                true),
  (1, 313, 'Summer Excursion & Sight Seeing Vessel',   'Wine',                true),
  (1, 314, 'Winter Excursion & Sight Seeing Vessels',  'Wine',                true),
  (1, 315, 'Tavern Miscellaneous',                     'Wine',                true),
  (1, 316, 'Summer - Tavern Miscellaneous',            'Wine',                true),
  (1, 317, 'Winter - Tavern Miscellaneous',            'Wine',                true),
  (1, 340, 'Restaurant',                               'Liquor',              true),
  (1, 341, 'Summer Restaurant',                        'Liquor',              true),
  (1, 342, 'Winter Restaurant',                        'Liquor',              true),
  (1, 343, 'Hotel',                                    'Liquor',              true),
  (1, 344, 'Summer Hotel Liquor',                      'Liquor',              true),
  (1, 345, 'Winter Hotel Liquor',                      'Liquor',              true),
  (1, 346, 'Catering Establishment',                   'Liquor',              true),
  (1, 347, 'Summer Catering Establishment',            'Liquor',              true),
  (1, 348, 'Winter Catering Establishment',            'Liquor',              true),
  (1, 349, 'Club',                                     'Liquor',              true),
  (1, 350, 'Summer Club',                              'Liquor',              true),
  (1, 351, 'Winter Club',                              'Liquor',              true),
  (1, 352, 'Luncheon Club',                            'Liquor',              true),
  (1, 353, 'Summer Luncheon Club',                     'Liquor',              true),
  (1, 354, 'Winter Luncheon Club',                     'Liquor',              true),
  (1, 355, 'Golf Club',                                'Liquor',              true),
  (1, 356, 'Summer Golf Club',                         'Liquor',              true),
  (1, 357, 'Winter Golf Club',                         'Liquor',              true),
  (1, 358, 'Railroad car',                             'Liquor',              true),
  (1, 359, 'Summer Railroad car',                      'Liquor',              true),
  (1, 360, 'Winter Railroad Car',                      'Liquor',              true),
  (1, 361, 'Vessel',                                   'Liquor',              true),
  (1, 362, 'Summer Vessel',                            'Liquor',              true),
  (1, 363, 'Winter Vessel',                            'Liquor',              true),
  (1, 364, 'Aircraft',                                 'Liquor',              true),
  (1, 365, 'Summer Aircraft',                          'Liquor',              true),
  (1, 366, 'Winter Aircraft',                          'Liquor',              true),
  (1, 367, 'Bed & Breakfast',                          'Liquor',              true),
  (1, 368, 'Summer Bed & Breakfast',                   'Liquor',              true),
  (1, 369, 'Winter Bed & Breakfast',                   'Liquor',              true),
  (1, 370, 'Food & Beverage Business',                 'Liquor',              true),
  (1, 371, 'Summer Food & beverage business',          'Liquor',              true),
  (1, 372, 'Winter Food & Beverage Business',          'Liquor',              true),
  (1, 373, 'Legitimate theatre',                       'Liquor',              true),
  (1, 374, 'Summer Legitimate theatre',                'Liquor',              true),
  (1, 375, 'Winter Legitimate Theatre',                'Liquor',              true),
  (1, 376, 'Concert Hall',                             'Liquor',              true),
  (1, 377, 'Summer Concert hall',                      'Liquor',              true),
  (1, 378, 'Winter Concert Hall',                      'Liquor',              true),
  (1, 379, 'Opera House',                              'Liquor',              true),
  (1, 380, 'Summer Opera House',                       'Liquor',              true),
  (1, 381, 'Winter Opera House',                       'Liquor',              true),
  (1, 382, 'Bowling Establishment',                    'Liquor',              true),
  (1, 383, 'Summer Bowling Establishment',             'Liquor',              true),
  (1, 384, 'Winter Bowling Establishment',             'Liquor',              true),
  (1, 385, 'Public Dance Hall',                        'Liquor',              true),
  (1, 386, 'Summer Public Dance Hall',                 'Liquor',              true),
  (1, 387, 'Winter Public Dance Hall',                 'Liquor',              true),
  (1, 388, 'Night Club',                               'Liquor',              true),
  (1, 389, 'Summer Night Club',                        'Liquor',              true),
  (1, 390, 'Winter Night Club',                        'Liquor',              true),
  (1, 391, 'Golf Venue',                               'Liquor',              true),
  (1, 392, 'Summer Golf Venue',                        'Liquor',              true),
  (1, 393, 'Winter Golf Venue',                        'Liquor',              true),
  (1, 394, 'Tennis Venue',                             'Liquor',              true),
  (1, 395, 'Summer Tennis Venue',                      'Liquor',              true),
  (1, 396, 'Winter Tennis Venue',                      'Liquor',              true),
  (1, 397, 'Swimming Venue',                           'Liquor',              true),
  (1, 398, 'Summer Swimming Venue',                    'Liquor',              true),
  (1, 399, 'Winter Swimming Venue',                    'Liquor',              true),
  (1, 400, 'Skiing Venue',                             'Liquor',              true),
  (1, 401, 'Summer Skiing Venue',                      'Liquor',              true),
  (1, 402, 'Winter Skiing Venue',                      'Liquor',              true),
  (1, 403, 'Ice Skating Venue',                        'Liquor',              true),
  (1, 404, 'Summer Ice Skating Venue',                 'Liquor',              true),
  (1, 405, 'Winter Ice Skating Venue',                 'Liquor',              true),
  (1, 406, 'Boating Venue',                            'Liquor',              true),
  (1, 407, 'Summer Boating Venue',                     'Liquor',              true),
  (1, 408, 'Winter Boating Venue',                     'Liquor',              true),
  (1, 409, 'Athletic/Sporting Event/Expositions/Large Gathering Venue',       'Liquor', true),
  (1, 410, 'Summer Athletic/Sporting Event/Expositions/Large Gathering Venue','Liquor', true),
  (1, 411, 'Winter Athletic/Sporting Event/Expositions/Large Gathering Venue','Liquor', true),
  (1, 412, 'Excursion & Sight Seeing Vessels',         'Liquor',              true),
  (1, 413, 'Summer Excursion & Sight Seeing Vessel',   'Liquor',              true),
  (1, 414, 'Winter Excursion & Sight Seeing Vessels',  'Liquor',              true),
  (1, 415, 'Bottle Club',                              'Liquor',              true),
  (1, 416, 'Restaurant Brewer',                        'Liquor',              true),
  (1, 417, 'Cabaret',                                  'Liquor',              true),
  (1, 419, 'Race Tracks',                              'Liquor',              true),
  (1, 420, 'Summer Race Tracks',                       'Liquor',              true),
  (1, 421, 'Winter Race Tracks',                       'Liquor',              true),
  (1, 422, 'Additional bar- legitimate theater',       NULL,                  true),
  (1, 423, 'Additional Bar',                           NULL,                  true),
  (1, 426, 'Additional Bar-Seasonal',                  NULL,                  true)
ON CONFLICT (type_code, class_code) DO UPDATE SET
  class_description = EXCLUDED.class_description,
  product           = EXCLUDED.product,
  not_bodega        = EXCLUDED.not_bodega;
